Updated ReadMe #11977
arduino/Arduino pull request #11987
Opened 2024-10-18 09:03 UTC by VarshiniShreeV

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/arduino/Arduino/pulls?q=) for the same update/change?

2024-10-18 09:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino/Arduino?pullRequest=11987) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino/Arduino?pullRequest=11987) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino/Arduino?pullRequest=11987) it.</sub>

2024-10-18 12:56 UTC, per1234 requested changes

2024-10-18 12:56 UTC, per1234 commented on README.md
> +**Important Notice**: This repository contains the legacy Arduino IDE, which is no longer in active development. For the latest features and updates, please visit the [Arduino IDE 2](https://github.c
```suggestion
**Important Notice**: This repository contains the legacy Arduino IDE 1.x, which is no longer in active development. For the latest features and updates, please visit the [Arduino IDE 2.x](https://github.com/arduino/arduino-ide) repository. If you encounter issues related to the newer IDE, please report them there.
```

Calling it "Arduino IDE 2" implies that is the name of the application. _It is not._ We present it as a new version series of the same Arduino IDE application. For this reason, it must always be referred to either as "Arduino IDE" or, in a case like this where we need to specify the version range, as "Arduino IDE 2.x".

2024-10-18 16:31 UTC, per1234 approved these changes
Thanks @VarshiniShreeV!

2024-10-18 16:32 UTC, merged

2025-04-24 05:23 UTC, EMMANUEL2811UNITEC approved these changes